import type { Metadata } from "next";
import { CTA, PageHero, SectionHeader } from "../components/Shared";

export const metadata: Metadata = { title: "Our Approach", description: "A practical five-stage restaurant consulting process: assessment, prioritization, implementation, leadership development, and long-term sustainability.", alternates: { canonical: "/our-approach" } };
const stages = [
  { n: "01", title: "Assessment", subtitle: "See the operation without filters.", text: "We study daily execution, leadership behavior, operating controls, financial signals, and the guest experience. The objective is a shared, fact-based view of what is helping performance and what is holding it back.", focus: ["On-site observation", "Leadership interviews", "Performance review", "Standards and controls"] },
  { n: "02", title: "Prioritization", subtitle: "Focus effort where it will matter.", text: "Restaurants can generate a long list of problems. We narrow the work to the operating causes with the greatest effect on consistency, margins, leadership, and guest trust.", focus: ["Root causes", "Operating priorities", "Clear ownership", "Practical measures"] },
  { n: "03", title: "Implementation", subtitle: "Put the work into the week.", text: "MHG works alongside leaders to install the routines, tools, standards, and conversations required for better execution. Progress is measured in behavior and results—not presentation slides.", focus: ["Management rhythms", "Tools and playbooks", "Coaching in context", "Progress visibility"] },
  { n: "04", title: "Leadership Development", subtitle: "Strengthen the people responsible for the standard.", text: "Managers learn how to inspect, coach, decide, and hold accountability. This is how the operation becomes less dependent on owner presence or outside support.", focus: ["Role clarity", "Decision quality", "Direct feedback", "Bench strength"] },
  { n: "05", title: "Long-term Sustainability", subtitle: "Make strong performance repeatable.", text: "We reinforce the operating model, transfer ownership, and ensure the team can identify drift early. The goal is durable capability, not consultant dependence.", focus: ["Leader ownership", "Early warning indicators", "Continuous improvement", "Scalable systems"] },
];

export default function ApproachPage() {
  return <><PageHero eyebrow="The MHG method" title="Our Approach" intro="Restaurant improvement becomes sustainable when clear priorities, strong leaders, and disciplined follow-through become part of the operation." /><section className="section"><div className="shell approach-intro"><SectionHeader eyebrow="How we engage" title="Disciplined enough to create accountability. Practical enough to work on the floor." /><p>Every engagement is shaped around the restaurant’s real situation. The sequence remains consistent because it keeps the work honest: understand first, focus second, implement with leaders, and transfer ownership.</p></div></section><section className="section section-tint"><div className="shell stage-list">{stages.map((stage) => <article key={stage.n}><div className="stage-number">{stage.n}</div><div><p className="card-kicker">{stage.title}</p><h2>{stage.subtitle}</h2><p>{stage.text}</p></div><ul>{stage.focus.map((item) => <li key={item}>{item}</li>)}</ul></article>)}</div></section><section className="section discipline-section"><div className="shell"><SectionHeader eyebrow="What holds the work together" title="Operational discipline is the through line." align="center" /><div className="discipline-grid"><div><strong>Execution</strong><span>Make expectations observable.</span></div><div><strong>Accountability</strong><span>Assign real ownership.</span></div><div><strong>Leadership</strong><span>Build judgment and follow-through.</span></div><div><strong>Consistency</strong><span>Reduce dependence on individuals.</span></div><div><strong>Margins</strong><span>Manage the controllable work.</span></div><div><strong>Guest Experience</strong><span>Protect hospitality in every decision.</span></div></div></div></section><CTA /></>;
}
