import type { Metadata } from "next";
import { notFound } from "next/navigation";
import { Breadcrumbs, CTA, Eyebrow, FAQSection, SectionHeader } from "../../components/Shared";
import { faqSchema, locationMap, locations } from "../../lib/seo";
import { site } from "../../lib/site";

export function generateStaticParams() { return locations.map((item) => ({ slug: item.slug })); }
export async function generateMetadata({ params }: { params: Promise<{ slug: string }> }): Promise<Metadata> { const { slug } = await params; const item = locationMap[slug]; if (!item) return {}; return { title: item.title, description: item.description, alternates: { canonical: `/locations/${slug}` }, openGraph: { title: item.title, description: item.description, url: `/locations/${slug}` } }; }
export default async function LocationPage({ params }: { params: Promise<{ slug: string }> }) { const { slug } = await params; const item = locationMap[slug]; if (!item) notFound(); const schema = { "@context": "https://schema.org", "@type": "Service", name: item.title, description: item.description, provider: { "@id": `${site.url}/#organization` }, areaServed: item.markets.map((market) => ({ "@type": "Place", name: market })), url: `${site.url}/locations/${slug}` }; return <><section className="service-hero"><div className="shell"><Breadcrumbs items={[{ label: "Home", href: "/" }, { label: "Service Areas", href: "/locations" }, { label: item.name }]} /><div className="service-hero-grid"><div><Eyebrow light>Regional restaurant consulting</Eyebrow><h1>{item.title}</h1><p>{item.description}</p></div><aside><span>How we support the market</span><p>{item.intro}</p></aside></div></div></section><section className="section"><div className="shell regional-grid"><div><SectionHeader eyebrow="Operating context" title={`Restaurant leadership for ${item.name}.`} /><p className="large-copy">{item.intro}</p></div><div className="market-list"><p className="card-kicker">Markets and operating contexts</p>{item.markets.map((market) => <span key={market}>{market}</span>)}</div></div></section><section className="section section-tint"><div className="shell"><SectionHeader eyebrow="Regional operating priorities" title="Local conditions still require disciplined systems." /><div className="priority-grid">{item.considerations.map((consideration, index) => <article key={consideration.title}><span>{String(index + 1).padStart(2, "0")}</span><h2>{consideration.title}</h2><p>{consideration.text}</p></article>)}</div></div></section><FAQSection items={item.faqs} /><CTA /><script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(schema) }} /><script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(faqSchema(item.faqs)) }} /></>; }
