import type { Metadata } from "next";
import { notFound } from "next/navigation";
import { ArrowLink, Breadcrumbs, CTA, Eyebrow, FAQSection } from "../../components/Shared";
import { faqSchema, insightMap, insights } from "../../lib/seo";
import { serviceMap, site } from "../../lib/site";

export function generateStaticParams() { return insights.map((item) => ({ slug: item.slug })); }
export async function generateMetadata({ params }: { params: Promise<{ slug: string }> }): Promise<Metadata> { const { slug } = await params; const item = insightMap[slug]; if (!item) return {}; return { title: item.title, description: item.description, alternates: { canonical: `/insights/${slug}` }, openGraph: { type: "article", title: item.title, description: item.description, url: `/insights/${slug}` } }; }
export default async function InsightPage({ params }: { params: Promise<{ slug: string }> }) { const { slug } = await params; const item = insightMap[slug]; if (!item) notFound(); const related = item.relatedServices.map((key) => serviceMap[key]).filter(Boolean); const articleSchema = { "@context": "https://schema.org", "@type": "Article", headline: item.title, description: item.description, author: { "@id": `${site.url}/#organization` }, publisher: { "@id": `${site.url}/#organization` }, mainEntityOfPage: `${site.url}/insights/${slug}`, datePublished: "2026-08-04", dateModified: "2026-08-04" }; return <><article><header className="insight-hero"><div className="shell"><Breadcrumbs items={[{ label: "Home", href: "/" }, { label: "Insights", href: "/insights" }, { label: item.title }]} /><div className="insight-hero-copy"><Eyebrow light>{item.category}</Eyebrow><h1>{item.title}</h1><p>{item.description}</p><div className="article-meta"><span>MHG Operating Insights</span><span>Executive briefing</span></div></div></div></header><div className="shell article-layout"><aside><p className="card-kicker">Executive takeaway</p><p>{item.takeaway}</p><nav aria-label="On this page"><span>In this guide</span>{item.sections.map((section) => <a key={section.heading} href={`#${section.heading.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "")}`}>{section.heading}</a>)}</nav></aside><div className="article-body">{item.sections.map((section) => <section key={section.heading} id={section.heading.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "")}><h2>{section.heading}</h2>{section.paragraphs.map((paragraph) => <p key={paragraph}>{paragraph}</p>)}{section.points && <ul>{section.points.map((point) => <li key={point}>{point}</li>)}</ul>}</section>)}</div></div></article><FAQSection items={item.questions} title="Direct answers to common operating questions." /><section className="section section-tint"><div className="shell"><p className="eyebrow"><span></span>Related consulting services</p><div className="related-grid">{related.map((service) => <article key={service.slug}><p className="card-kicker">{service.eyebrow}</p><h3>{service.name}</h3><p>{service.summary}</p><ArrowLink href={`/services/${service.slug}`}>Explore service</ArrowLink></article>)}</div></div></section><CTA /><script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(articleSchema) }} /><script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(faqSchema(item.questions)) }} /></>;
}
